<a href="https://colab.research.google.com/github/Mahdi-Miri/Pytorch-Tutorial/blob/main/Pytorch-Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [163]:
!pip install torch torchvision -U

In [164]:
import torch

print(torch.__version__)

2.5.1+cu121


In [165]:
data = [[1,2],[3,4],[5,6]]

In [166]:
data

[[1, 2], [3, 4], [5, 6]]

In [167]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [168]:
x = torch.zeros((3,3,5),dtype=torch.float16)

In [169]:
x

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16)

In [170]:
x[1]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [171]:
shape = (2,3,4)

In [172]:
x = torch.ones(shape)

In [173]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [174]:
x = torch.rand(shape)

In [175]:
x

tensor([[[0.1678, 0.0907, 0.3730, 0.9367],
         [0.1429, 0.6304, 0.8651, 0.3990],
         [0.9952, 0.0069, 0.2413, 0.6625]],

        [[0.2788, 0.9685, 0.0628, 0.1618],
         [0.0214, 0.2846, 0.5584, 0.0572],
         [0.0275, 0.2971, 0.9953, 0.1856]]])

In [176]:
x = torch.tensor(([1,2,3,4,5],[5,4,3,2,1]))

In [177]:
x

tensor([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]])

In [178]:
x *2

tensor([[ 2,  4,  6,  8, 10],
        [10,  8,  6,  4,  2]])

In [179]:
x.shape

torch.Size([2, 5])

In [180]:
x.dtype

torch.int64

In [181]:
x.device

device(type='cpu')

In [182]:
x[0]

tensor([1, 2, 3, 4, 5])

In [183]:
x[ : ,  0]

tensor([1, 5])

In [184]:
x[...,-1]

tensor([5, 1])

# Joining Tensors

In [185]:
shape1 = (4,6,5)
shape2 = (4,5,6)

In [186]:
tensor1  = torch.rand(shape1)

In [187]:
tensor2 = torch.rand(shape2)

In [188]:
print("Tensor 1 :")
tensor1

Tensor 1 :


tensor([[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

        [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
         [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
         [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
         [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
         [0.6302, 0.7248, 0.6897, 0.5003, 0.4307]],

        [[0.7849, 0.9960, 0.1871, 0.1482, 0.5056],
         [0.5415, 0.8152, 0.5039, 0.5330, 0.7944],
         [0.1168, 0.4035, 0.9385, 0.8188, 0.7750],
         [0.0426, 0.8974, 0.4699, 0.0680, 0.4345],
         [0.7019, 0.2508, 0.9879, 0.3802, 0.2828],
         [0.9271, 0.9763, 0.2186, 0.6143, 0.5616]],

        [[0.7126, 0.9044, 0.0419, 0.8656, 0.0775],
         [0.6918, 0.0702,

In [189]:
print("Tensor 2 :")
tensor2

Tensor 2 :


tensor([[[0.8396, 0.6734, 0.8279, 0.3794, 0.6060, 0.7280],
         [0.6215, 0.4567, 0.6064, 0.3079, 0.0068, 0.7194],
         [0.5991, 0.8122, 0.0027, 0.0733, 0.0384, 0.9620],
         [0.4014, 0.6193, 0.7549, 0.2678, 0.5458, 0.4503],
         [0.8710, 0.3680, 0.4298, 0.8911, 0.5361, 0.3030]],

        [[0.2943, 0.6098, 0.5279, 0.0780, 0.7563, 0.7404],
         [0.6850, 0.0887, 0.9375, 0.8603, 0.2632, 0.0348],
         [0.9875, 0.7975, 0.1299, 0.3891, 0.4430, 0.0557],
         [0.2928, 0.8977, 0.6926, 0.4441, 0.5700, 0.2825],
         [0.9504, 0.0721, 0.1095, 0.3118, 0.3465, 0.3688]],

        [[0.3626, 0.2493, 0.0029, 0.5279, 0.2737, 0.6057],
         [0.4519, 0.9852, 0.1996, 0.1786, 0.9814, 0.8094],
         [0.5238, 0.0662, 0.6554, 0.4895, 0.6356, 0.1602],
         [0.7752, 0.6563, 0.7701, 0.1641, 0.0679, 0.8189],
         [0.0642, 0.3461, 0.2518, 0.3615, 0.8993, 0.9408]],

        [[0.2996, 0.5459, 0.5998, 0.5795, 0.4748, 0.4490],
         [0.7243, 0.2937, 0.3699, 0.7137, 0.2658, 

In [190]:
t1 = torch.cat([tensor1,tensor1],dim =1)

In [191]:
t1

tensor([[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403],
         [0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

        [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
         [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
         [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
         [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
         [0.6302, 0.7248, 0.6897, 0.5003, 0.4307],
         [0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0

In [192]:
t1 = torch.cat([tensor1,tensor1],dim =0)

In [193]:
t1

tensor([[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

        [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
         [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
         [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
         [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
         [0.6302, 0.7248, 0.6897, 0.5003, 0.4307]],

        [[0.7849, 0.9960, 0.1871, 0.1482, 0.5056],
         [0.5415, 0.8152, 0.5039, 0.5330, 0.7944],
         [0.1168, 0.4035, 0.9385, 0.8188, 0.7750],
         [0.0426, 0.8974, 0.4699, 0.0680, 0.4345],
         [0.7019, 0.2508, 0.9879, 0.3802, 0.2828],
         [0.9271, 0.9763, 0.2186, 0.6143, 0.5616]],

        [[0.7126, 0.9044, 0.0419, 0.8656, 0.0775],
         [0.6918, 0.0702,

In [194]:
t1 = torch.stack([tensor1,tensor1])

In [195]:
t1

tensor([[[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
          [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
          [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
          [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
          [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
          [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

         [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
          [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
          [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
          [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
          [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
          [0.6302, 0.7248, 0.6897, 0.5003, 0.4307]],

         [[0.7849, 0.9960, 0.1871, 0.1482, 0.5056],
          [0.5415, 0.8152, 0.5039, 0.5330, 0.7944],
          [0.1168, 0.4035, 0.9385, 0.8188, 0.7750],
          [0.0426, 0.8974, 0.4699, 0.0680, 0.4345],
          [0.7019, 0.2508, 0.9879, 0.3802, 0.2828],
          [0.9271, 0.9763, 0.2186, 0.6143, 0.5616]],

         [[0.7126, 0.9044, 0.0419, 0.8656, 0.0775],
      

In [196]:
tensor1 @ tensor2

tensor([[[1.5852, 1.4591, 1.1627, 0.8263, 0.7265, 1.6252],
         [1.8879, 1.5294, 1.8592, 1.2690, 1.0787, 1.6244],
         [1.4493, 0.9755, 1.0575, 1.0652, 0.6742, 1.0932],
         [1.8548, 1.4042, 1.0350, 1.1936, 0.7512, 1.5950],
         [2.5074, 2.3542, 2.1681, 1.3194, 1.3193, 2.5578],
         [1.9465, 1.5729, 1.8266, 1.2622, 1.0566, 1.7064]],

        [[1.6187, 1.5077, 1.3593, 1.1522, 1.3080, 0.7717],
         [0.7323, 0.4349, 0.4481, 0.3464, 0.5811, 0.5040],
         [1.6139, 0.7924, 1.0671, 1.1697, 0.7648, 0.2775],
         [2.0941, 1.9788, 1.5791, 1.2496, 1.8215, 1.2289],
         [1.8022, 1.1594, 1.3485, 1.3047, 1.1026, 0.5624],
         [1.9189, 1.4787, 1.4955, 1.2976, 1.4074, 0.8305]],

        [[0.9800, 1.4615, 0.5651, 0.8909, 1.7759, 1.9085],
         [1.2929, 1.5963, 1.1050, 1.0528, 2.0191, 2.2524],
         [1.4008, 1.2944, 1.5217, 1.0077, 1.7770, 1.9473],
         [0.7478, 1.1209, 0.6490, 0.5810, 1.5864, 1.2919],
         [1.1982, 0.8348, 1.0636, 1.0635, 1.3462, 1.

In [197]:
tensor1.T

tensor([[[0.4523, 0.3545, 0.7849, 0.7126],
         [0.4146, 0.3892, 0.5415, 0.6918],
         [0.1956, 0.0763, 0.1168, 0.3249],
         [0.2844, 0.8446, 0.0426, 0.5323],
         [0.8567, 0.2369, 0.7019, 0.0063],
         [0.4920, 0.6302, 0.9271, 0.0115]],

        [[0.5243, 0.4158, 0.9960, 0.9044],
         [0.9660, 0.1072, 0.8152, 0.0702],
         [0.6508, 0.8705, 0.4035, 0.9094],
         [0.5521, 0.3093, 0.8974, 0.7073],
         [0.8934, 0.7946, 0.2508, 0.9665],
         [0.9654, 0.7248, 0.9763, 0.8729]],

        [[0.6462, 0.4423, 0.1871, 0.0419],
         [0.0442, 0.0588, 0.5039, 0.6816],
         [0.1519, 0.6639, 0.9385, 0.7324],
         [0.6970, 0.6306, 0.4699, 0.6949],
         [0.7528, 0.5711, 0.9879, 0.8012],
         [0.1317, 0.6897, 0.2186, 0.6484]],

        [[0.4050, 0.9615, 0.1482, 0.8656],
         [0.8613, 0.1191, 0.5330, 0.1902],
         [0.1990, 0.1296, 0.8188, 0.0988],
         [0.0733, 0.9786, 0.0680, 0.9074],
         [0.9505, 0.5044, 0.3802, 0.8479],
     

In [198]:
tensor2 * tensor2

tensor([[[7.0498e-01, 4.5345e-01, 6.8541e-01, 1.4395e-01, 3.6720e-01,
          5.2993e-01],
         [3.8620e-01, 2.0859e-01, 3.6772e-01, 9.4797e-02, 4.5861e-05,
          5.1752e-01],
         [3.5887e-01, 6.5965e-01, 7.2934e-06, 5.3662e-03, 1.4751e-03,
          9.2538e-01],
         [1.6114e-01, 3.8353e-01, 5.6985e-01, 7.1739e-02, 2.9790e-01,
          2.0277e-01],
         [7.5860e-01, 1.3546e-01, 1.8474e-01, 7.9404e-01, 2.8739e-01,
          9.1784e-02]],

        [[8.6602e-02, 3.7183e-01, 2.7872e-01, 6.0832e-03, 5.7205e-01,
          5.4824e-01],
         [4.6924e-01, 7.8616e-03, 8.7890e-01, 7.4019e-01, 6.9285e-02,
          1.2135e-03],
         [9.7514e-01, 6.3599e-01, 1.6870e-02, 1.5142e-01, 1.9623e-01,
          3.1006e-03],
         [8.5713e-02, 8.0582e-01, 4.7973e-01, 1.9720e-01, 3.2487e-01,
          7.9826e-02],
         [9.0326e-01, 5.1995e-03, 1.1986e-02, 9.7192e-02, 1.2009e-01,
          1.3601e-01]],

        [[1.3148e-01, 6.2144e-02, 8.3886e-06, 2.7869e-01, 7.4885e-

In [199]:
tensor1 / 2

tensor([[[0.2262, 0.2622, 0.3231, 0.2025, 0.1894],
         [0.2073, 0.4830, 0.0221, 0.4307, 0.3256],
         [0.0978, 0.3254, 0.0759, 0.0995, 0.4075],
         [0.1422, 0.2761, 0.3485, 0.0366, 0.4742],
         [0.4283, 0.4467, 0.3764, 0.4753, 0.2298],
         [0.2460, 0.4827, 0.0659, 0.3698, 0.3202]],

        [[0.1773, 0.2079, 0.2211, 0.4808, 0.2690],
         [0.1946, 0.0536, 0.0294, 0.0595, 0.2375],
         [0.0382, 0.4352, 0.3320, 0.0648, 0.1587],
         [0.4223, 0.1547, 0.3153, 0.4893, 0.3811],
         [0.1185, 0.3973, 0.2855, 0.2522, 0.2507],
         [0.3151, 0.3624, 0.3449, 0.2501, 0.2154]],

        [[0.3924, 0.4980, 0.0936, 0.0741, 0.2528],
         [0.2708, 0.4076, 0.2519, 0.2665, 0.3972],
         [0.0584, 0.2017, 0.4692, 0.4094, 0.3875],
         [0.0213, 0.4487, 0.2349, 0.0340, 0.2172],
         [0.3510, 0.1254, 0.4940, 0.1901, 0.1414],
         [0.4635, 0.4882, 0.1093, 0.3072, 0.2808]],

        [[0.3563, 0.4522, 0.0210, 0.4328, 0.0387],
         [0.3459, 0.0351,

# Getting Value Of Single-Element Tensor

In [200]:
tensor1

tensor([[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

        [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
         [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
         [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
         [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
         [0.6302, 0.7248, 0.6897, 0.5003, 0.4307]],

        [[0.7849, 0.9960, 0.1871, 0.1482, 0.5056],
         [0.5415, 0.8152, 0.5039, 0.5330, 0.7944],
         [0.1168, 0.4035, 0.9385, 0.8188, 0.7750],
         [0.0426, 0.8974, 0.4699, 0.0680, 0.4345],
         [0.7019, 0.2508, 0.9879, 0.3802, 0.2828],
         [0.9271, 0.9763, 0.2186, 0.6143, 0.5616]],

        [[0.7126, 0.9044, 0.0419, 0.8656, 0.0775],
         [0.6918, 0.0702,

In [201]:
tensor1[0,1,2].item()

0.044235825538635254

# Inplace Operation

In [202]:
tensor1

tensor([[[0.4523, 0.5243, 0.6462, 0.4050, 0.3787],
         [0.4146, 0.9660, 0.0442, 0.8613, 0.6513],
         [0.1956, 0.6508, 0.1519, 0.1990, 0.8149],
         [0.2844, 0.5521, 0.6970, 0.0733, 0.9483],
         [0.8567, 0.8934, 0.7528, 0.9505, 0.4597],
         [0.4920, 0.9654, 0.1317, 0.7396, 0.6403]],

        [[0.3545, 0.4158, 0.4423, 0.9615, 0.5380],
         [0.3892, 0.1072, 0.0588, 0.1191, 0.4749],
         [0.0763, 0.8705, 0.6639, 0.1296, 0.3174],
         [0.8446, 0.3093, 0.6306, 0.9786, 0.7623],
         [0.2369, 0.7946, 0.5711, 0.5044, 0.5014],
         [0.6302, 0.7248, 0.6897, 0.5003, 0.4307]],

        [[0.7849, 0.9960, 0.1871, 0.1482, 0.5056],
         [0.5415, 0.8152, 0.5039, 0.5330, 0.7944],
         [0.1168, 0.4035, 0.9385, 0.8188, 0.7750],
         [0.0426, 0.8974, 0.4699, 0.0680, 0.4345],
         [0.7019, 0.2508, 0.9879, 0.3802, 0.2828],
         [0.9271, 0.9763, 0.2186, 0.6143, 0.5616]],

        [[0.7126, 0.9044, 0.0419, 0.8656, 0.0775],
         [0.6918, 0.0702,

In [203]:
tensor1.add_(75)

tensor([[[75.4523, 75.5243, 75.6462, 75.4050, 75.3787],
         [75.4146, 75.9660, 75.0442, 75.8613, 75.6513],
         [75.1956, 75.6508, 75.1519, 75.1990, 75.8149],
         [75.2844, 75.5521, 75.6970, 75.0733, 75.9483],
         [75.8567, 75.8934, 75.7528, 75.9505, 75.4597],
         [75.4920, 75.9654, 75.1317, 75.7396, 75.6403]],

        [[75.3545, 75.4158, 75.4423, 75.9615, 75.5380],
         [75.3892, 75.1072, 75.0588, 75.1191, 75.4749],
         [75.0763, 75.8705, 75.6639, 75.1296, 75.3174],
         [75.8446, 75.3093, 75.6306, 75.9787, 75.7623],
         [75.2369, 75.7946, 75.5711, 75.5044, 75.5014],
         [75.6302, 75.7248, 75.6897, 75.5003, 75.4307]],

        [[75.7849, 75.9960, 75.1871, 75.1482, 75.5056],
         [75.5415, 75.8152, 75.5039, 75.5330, 75.7944],
         [75.1168, 75.4035, 75.9385, 75.8188, 75.7750],
         [75.0426, 75.8974, 75.4699, 75.0680, 75.4345],
         [75.7019, 75.2507, 75.9879, 75.3802, 75.2828],
         [75.9271, 75.9763, 75.2186, 75.6143

# Tensor Views

In [206]:
tensor1.shape

torch.Size([4, 6, 5])

In [207]:
tensor1.view([4,5,6])

tensor([[[75.4523, 75.5243, 75.6462, 75.4050, 75.3787, 75.4146],
         [75.9660, 75.0442, 75.8613, 75.6513, 75.1956, 75.6508],
         [75.1519, 75.1990, 75.8149, 75.2844, 75.5521, 75.6970],
         [75.0733, 75.9483, 75.8567, 75.8934, 75.7528, 75.9505],
         [75.4597, 75.4920, 75.9654, 75.1317, 75.7396, 75.6403]],

        [[75.3545, 75.4158, 75.4423, 75.9615, 75.5380, 75.3892],
         [75.1072, 75.0588, 75.1191, 75.4749, 75.0763, 75.8705],
         [75.6639, 75.1296, 75.3174, 75.8446, 75.3093, 75.6306],
         [75.9787, 75.7623, 75.2369, 75.7946, 75.5711, 75.5044],
         [75.5014, 75.6302, 75.7248, 75.6897, 75.5003, 75.4307]],

        [[75.7849, 75.9960, 75.1871, 75.1482, 75.5056, 75.5415],
         [75.8152, 75.5039, 75.5330, 75.7944, 75.1168, 75.4035],
         [75.9385, 75.8188, 75.7750, 75.0426, 75.8974, 75.4699],
         [75.0680, 75.4345, 75.7019, 75.2507, 75.9879, 75.3802],
         [75.2828, 75.9271, 75.9763, 75.2186, 75.6143, 75.5616]],

        [[75.7126, 

In [208]:
tensor1.shape

torch.Size([4, 6, 5])

# Gradient Descent

In [210]:
xg = torch.ones((5,2),requires_grad =True)

In [211]:
xg.requires_grad

True

In [212]:
xg

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [213]:
layer1 = xg + 2

In [214]:
layer1

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [215]:
layer2 = layer1 * 2

In [216]:
layer2

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>)

In [217]:
layer3 = layer2.mean()

In [218]:
layer3

tensor(6., grad_fn=<MeanBackward0>)

In [219]:
#deactivate

layer2_detach = layer2.detach()

In [220]:
layer2_detach

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]])