<a href="https://colab.research.google.com/github/Mahdi-Miri/Pytorch-Tutorial/blob/main/Pytorch-Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision -U

In [2]:
import torch

print(torch.__version__)

2.5.1+cu121


In [3]:
data = [[1,2],[3,4],[5,6]]

In [4]:
data

[[1, 2], [3, 4], [5, 6]]

In [5]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
x = torch.zeros((3,3,5),dtype=torch.float16)

In [18]:
x

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16)

In [19]:
x[1]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [21]:
shape = (2,3,4)

In [22]:
x = torch.ones(shape)

In [23]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [24]:
x = torch.rand(shape)

In [25]:
x

tensor([[[0.4614, 0.4813, 0.6929, 0.5494],
         [0.6891, 0.7991, 0.3800, 0.7510],
         [0.8111, 0.2988, 0.5639, 0.3903]],

        [[0.1577, 0.3950, 0.7497, 0.0530],
         [0.7528, 0.5905, 0.0059, 0.4633],
         [0.7369, 0.4175, 0.0592, 0.6505]]])

In [34]:
x = torch.tensor(([1,2,3,4,5],[5,4,3,2,1]))

In [35]:
x

tensor([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]])

In [36]:
x *2

tensor([[ 2,  4,  6,  8, 10],
        [10,  8,  6,  4,  2]])