<a href="https://colab.research.google.com/github/Mahdi-Miri/Pytorch-Tutorial/blob/main/Pytorch-Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision -U

In [2]:
import torch

print(torch.__version__)

2.5.1+cu121


In [3]:
data = [[1,2],[3,4],[5,6]]

In [4]:
data

[[1, 2], [3, 4], [5, 6]]

In [5]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
x = torch.zeros((3,3,5),dtype=torch.float16)

In [7]:
x

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16)

In [8]:
x[1]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [9]:
shape = (2,3,4)

In [10]:
x = torch.ones(shape)

In [11]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
x = torch.rand(shape)

In [13]:
x

tensor([[[0.6233, 0.7922, 0.3389, 0.7360],
         [0.9745, 0.2200, 0.4751, 0.9833],
         [0.8499, 0.5000, 0.5383, 0.8131]],

        [[0.7369, 0.4701, 0.9441, 0.4701],
         [0.2337, 0.9430, 0.4120, 0.9792],
         [0.7077, 0.0162, 0.9838, 0.5388]]])

In [14]:
x = torch.tensor(([1,2,3,4,5],[5,4,3,2,1]))

In [15]:
x

tensor([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]])

In [16]:
x *2

tensor([[ 2,  4,  6,  8, 10],
        [10,  8,  6,  4,  2]])

In [17]:
x.shape

torch.Size([2, 5])

In [18]:
x.dtype

torch.int64

In [19]:
x.device

device(type='cpu')

In [20]:
x[0]

tensor([1, 2, 3, 4, 5])

In [21]:
x[ : ,  0]

tensor([1, 5])

In [22]:
x[...,-1]

tensor([5, 1])

# Joining Tensors

In [23]:
shape1 = (4,6,5)
shape2 = (4,5,6)

In [24]:
tensor1  = torch.rand(shape1)

In [25]:
tensor2 = torch.rand(shape2)

In [26]:
print("Tensor 1 :")
tensor1

Tensor 1 :


tensor([[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

        [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
         [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
         [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
         [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
         [0.2317, 0.6685, 0.2540, 0.4024, 0.8379]],

        [[0.1574, 0.5807, 0.6515, 0.2220, 0.3137],
         [0.3600, 0.9463, 0.8805, 0.3241, 0.1056],
         [0.5343, 0.0464, 0.4494, 0.8870, 0.4255],
         [0.5233, 0.9512, 0.7017, 0.7146, 0.9213],
         [0.5670, 0.3978, 0.3806, 0.3368, 0.1979],
         [0.8415, 0.7021, 0.7653, 0.6673, 0.0051]],

        [[0.0378, 0.2704, 0.7876, 0.1437, 0.8418],
         [0.6944, 0.8279,

In [27]:
print("Tensor 2 :")
tensor2

Tensor 2 :


tensor([[[0.4382, 0.6751, 0.8562, 0.6359, 0.3741, 0.3820],
         [0.0170, 0.0363, 0.0113, 0.1728, 0.2910, 0.5099],
         [0.7994, 0.9125, 0.9095, 0.2369, 0.5613, 0.5262],
         [0.3700, 0.6631, 0.7096, 0.9434, 0.4385, 0.6830],
         [0.7475, 0.3572, 0.3564, 0.1322, 0.1678, 0.2022]],

        [[0.3474, 0.9626, 0.9916, 0.9892, 0.9020, 0.0793],
         [0.8218, 0.5268, 0.1299, 0.9409, 0.3833, 0.1024],
         [0.4240, 0.6094, 0.5318, 0.5914, 0.5611, 0.6284],
         [0.6625, 0.0378, 0.0368, 0.7641, 0.1883, 0.1154],
         [0.4827, 0.0440, 0.1653, 0.1110, 0.4931, 0.2892]],

        [[0.8979, 0.2965, 0.4820, 0.5758, 0.8829, 0.0109],
         [0.6694, 0.8238, 0.9896, 0.6861, 0.2986, 0.7675],
         [0.8015, 0.0807, 0.8882, 0.9459, 0.6950, 0.8995],
         [0.0129, 0.6925, 0.8389, 0.2125, 0.8312, 0.1864],
         [0.5011, 0.1384, 0.2557, 0.2799, 0.3281, 0.5413]],

        [[0.8601, 0.3041, 0.8315, 0.5407, 0.7803, 0.3462],
         [0.3446, 0.4110, 0.0658, 0.4710, 0.2207, 

In [28]:
t1 = torch.cat([tensor1,tensor1],dim =1)

In [29]:
t1

tensor([[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043],
         [0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

        [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
         [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
         [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
         [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
         [0.2317, 0.6685, 0.2540, 0.4024, 0.8379],
         [0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8

In [30]:
t1 = torch.cat([tensor1,tensor1],dim =0)

In [31]:
t1

tensor([[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

        [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
         [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
         [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
         [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
         [0.2317, 0.6685, 0.2540, 0.4024, 0.8379]],

        [[0.1574, 0.5807, 0.6515, 0.2220, 0.3137],
         [0.3600, 0.9463, 0.8805, 0.3241, 0.1056],
         [0.5343, 0.0464, 0.4494, 0.8870, 0.4255],
         [0.5233, 0.9512, 0.7017, 0.7146, 0.9213],
         [0.5670, 0.3978, 0.3806, 0.3368, 0.1979],
         [0.8415, 0.7021, 0.7653, 0.6673, 0.0051]],

        [[0.0378, 0.2704, 0.7876, 0.1437, 0.8418],
         [0.6944, 0.8279,

In [32]:
t1 = torch.stack([tensor1,tensor1])

In [33]:
t1

tensor([[[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
          [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
          [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
          [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
          [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
          [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

         [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
          [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
          [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
          [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
          [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
          [0.2317, 0.6685, 0.2540, 0.4024, 0.8379]],

         [[0.1574, 0.5807, 0.6515, 0.2220, 0.3137],
          [0.3600, 0.9463, 0.8805, 0.3241, 0.1056],
          [0.5343, 0.0464, 0.4494, 0.8870, 0.4255],
          [0.5233, 0.9512, 0.7017, 0.7146, 0.9213],
          [0.5670, 0.3978, 0.3806, 0.3368, 0.1979],
          [0.8415, 0.7021, 0.7653, 0.6673, 0.0051]],

         [[0.0378, 0.2704, 0.7876, 0.1437, 0.8418],
      

In [34]:
tensor1 @ tensor2

tensor([[[1.3693, 1.6628, 1.8310, 1.5863, 1.1622, 1.5227],
         [1.4294, 1.3000, 1.2894, 0.5767, 0.9325, 1.0929],
         [1.4746, 1.4987, 1.6256, 1.2214, 1.0041, 1.2697],
         [1.3693, 1.6650, 1.8028, 1.0805, 1.2438, 1.4595],
         [1.4044, 1.8245, 1.9693, 1.5115, 1.2107, 1.4900],
         [1.4197, 1.5004, 1.5658, 1.0106, 1.0260, 1.2462]],

        [[1.0099, 0.6623, 0.5946, 1.1030, 0.8966, 0.4918],
         [2.0115, 1.6928, 1.5587, 2.5465, 2.0255, 1.0034],
         [1.4309, 1.0341, 0.8463, 1.9598, 1.1172, 0.4211],
         [0.7563, 0.9774, 0.8215, 1.2516, 0.9115, 0.2348],
         [1.2715, 0.8085, 0.4034, 1.5043, 0.7261, 0.4538],
         [1.4086, 0.7821, 0.6050, 1.4089, 1.0967, 0.5352]],

        [[1.2124, 0.7748, 1.4957, 1.2404, 1.0527, 1.2447],
         [1.7195, 1.1963, 2.1908, 1.7878, 1.5164, 1.6397],
         [1.0957, 0.9060, 1.5556, 1.0722, 1.6748, 0.8413],
         [2.1399, 1.6177, 2.6518, 2.0274, 2.1300, 1.9987],
         [1.1839, 0.7871, 1.3381, 1.0864, 1.2288, 0.

In [35]:
tensor1.T

<ipython-input-35-0fee77ff0160>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  tensor1.T


tensor([[[0.8078, 0.2534, 0.1574, 0.0378],
         [0.0143, 0.8702, 0.3600, 0.6944],
         [0.6436, 0.5814, 0.5343, 0.9020],
         [0.8894, 0.6662, 0.5233, 0.9485],
         [0.6401, 0.0078, 0.5670, 0.7305],
         [0.3233, 0.2317, 0.8415, 0.1456]],

        [[0.6459, 0.2842, 0.5807, 0.2704],
         [0.6283, 0.4829, 0.9463, 0.8279],
         [0.5130, 0.4981, 0.0464, 0.6192],
         [0.9791, 0.4263, 0.9512, 0.4839],
         [0.3695, 0.9327, 0.3978, 0.6974],
         [0.4958, 0.6685, 0.7021, 0.2869]],

        [[0.3772, 0.3764, 0.6515, 0.7876],
         [0.9982, 0.8749, 0.8805, 0.8265],
         [0.4084, 0.2787, 0.4494, 0.3620],
         [0.9876, 0.1719, 0.7017, 0.7806],
         [0.7914, 0.4794, 0.3806, 0.2110],
         [0.8027, 0.2540, 0.7653, 0.1490]],

        [[0.8512, 0.3935, 0.2220, 0.1437],
         [0.1297, 0.8129, 0.3241, 0.7811],
         [0.5411, 0.9642, 0.8870, 0.7746],
         [0.0925, 0.1085, 0.7146, 0.5098],
         [0.8740, 0.4358, 0.3368, 0.2650],
     

In [36]:
tensor2 * tensor2

tensor([[[1.9200e-01, 4.5582e-01, 7.3306e-01, 4.0440e-01, 1.3998e-01,
          1.4591e-01],
         [2.8832e-04, 1.3173e-03, 1.2722e-04, 2.9844e-02, 8.4688e-02,
          2.6004e-01],
         [6.3905e-01, 8.3263e-01, 8.2722e-01, 5.6115e-02, 3.1506e-01,
          2.7685e-01],
         [1.3690e-01, 4.3970e-01, 5.0356e-01, 8.9006e-01, 1.9225e-01,
          4.6654e-01],
         [5.5878e-01, 1.2760e-01, 1.2704e-01, 1.7487e-02, 2.8157e-02,
          4.0881e-02]],

        [[1.2068e-01, 9.2660e-01, 9.8322e-01, 9.7856e-01, 8.1361e-01,
          6.2853e-03],
         [6.7537e-01, 2.7757e-01, 1.6874e-02, 8.8536e-01, 1.4690e-01,
          1.0478e-02],
         [1.7978e-01, 3.7142e-01, 2.8279e-01, 3.4979e-01, 3.1479e-01,
          3.9483e-01],
         [4.3892e-01, 1.4292e-03, 1.3533e-03, 5.8390e-01, 3.5454e-02,
          1.3326e-02],
         [2.3299e-01, 1.9385e-03, 2.7322e-02, 1.2317e-02, 2.4318e-01,
          8.3656e-02]],

        [[8.0622e-01, 8.7908e-02, 2.3229e-01, 3.3154e-01, 7.7948e-

In [37]:
tensor1 / 2

tensor([[[0.4039, 0.3229, 0.1886, 0.4256, 0.2594],
         [0.0071, 0.3142, 0.4991, 0.0649, 0.3790],
         [0.3218, 0.2565, 0.2042, 0.2705, 0.4396],
         [0.4447, 0.4896, 0.4938, 0.0462, 0.0931],
         [0.3201, 0.1847, 0.3957, 0.4370, 0.1081],
         [0.1616, 0.2479, 0.4013, 0.2381, 0.3022]],

        [[0.1267, 0.1421, 0.1882, 0.1968, 0.2777],
         [0.4351, 0.2414, 0.4375, 0.4065, 0.4173],
         [0.2907, 0.2490, 0.1394, 0.4821, 0.0649],
         [0.3331, 0.2132, 0.0859, 0.0543, 0.0308],
         [0.0039, 0.4664, 0.2397, 0.2179, 0.0106],
         [0.1159, 0.3342, 0.1270, 0.2012, 0.4189]],

        [[0.0787, 0.2904, 0.3258, 0.1110, 0.1569],
         [0.1800, 0.4731, 0.4403, 0.1621, 0.0528],
         [0.2671, 0.0232, 0.2247, 0.4435, 0.2128],
         [0.2616, 0.4756, 0.3508, 0.3573, 0.4606],
         [0.2835, 0.1989, 0.1903, 0.1684, 0.0989],
         [0.4208, 0.3510, 0.3827, 0.3337, 0.0025]],

        [[0.0189, 0.1352, 0.3938, 0.0718, 0.4209],
         [0.3472, 0.4139,

# Getting Value Of Single-Element Tensor

In [38]:
tensor1

tensor([[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

        [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
         [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
         [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
         [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
         [0.2317, 0.6685, 0.2540, 0.4024, 0.8379]],

        [[0.1574, 0.5807, 0.6515, 0.2220, 0.3137],
         [0.3600, 0.9463, 0.8805, 0.3241, 0.1056],
         [0.5343, 0.0464, 0.4494, 0.8870, 0.4255],
         [0.5233, 0.9512, 0.7017, 0.7146, 0.9213],
         [0.5670, 0.3978, 0.3806, 0.3368, 0.1979],
         [0.8415, 0.7021, 0.7653, 0.6673, 0.0051]],

        [[0.0378, 0.2704, 0.7876, 0.1437, 0.8418],
         [0.6944, 0.8279,

In [39]:
tensor1[0,1,2].item()

0.9981913566589355

# Inplace Operation

In [40]:
tensor1

tensor([[[0.8078, 0.6459, 0.3772, 0.8512, 0.5188],
         [0.0143, 0.6283, 0.9982, 0.1297, 0.7579],
         [0.6436, 0.5130, 0.4084, 0.5411, 0.8792],
         [0.8894, 0.9791, 0.9876, 0.0925, 0.1862],
         [0.6401, 0.3695, 0.7914, 0.8740, 0.2162],
         [0.3233, 0.4958, 0.8027, 0.4763, 0.6043]],

        [[0.2534, 0.2842, 0.3764, 0.3935, 0.5554],
         [0.8702, 0.4829, 0.8749, 0.8129, 0.8346],
         [0.5814, 0.4981, 0.2787, 0.9642, 0.1297],
         [0.6662, 0.4263, 0.1719, 0.1085, 0.0616],
         [0.0078, 0.9327, 0.4794, 0.4358, 0.0212],
         [0.2317, 0.6685, 0.2540, 0.4024, 0.8379]],

        [[0.1574, 0.5807, 0.6515, 0.2220, 0.3137],
         [0.3600, 0.9463, 0.8805, 0.3241, 0.1056],
         [0.5343, 0.0464, 0.4494, 0.8870, 0.4255],
         [0.5233, 0.9512, 0.7017, 0.7146, 0.9213],
         [0.5670, 0.3978, 0.3806, 0.3368, 0.1979],
         [0.8415, 0.7021, 0.7653, 0.6673, 0.0051]],

        [[0.0378, 0.2704, 0.7876, 0.1437, 0.8418],
         [0.6944, 0.8279,

In [41]:
tensor1.add_(75)

tensor([[[75.8078, 75.6459, 75.3772, 75.8512, 75.5188],
         [75.0143, 75.6283, 75.9982, 75.1297, 75.7579],
         [75.6436, 75.5130, 75.4084, 75.5411, 75.8792],
         [75.8894, 75.9791, 75.9876, 75.0925, 75.1862],
         [75.6401, 75.3695, 75.7914, 75.8740, 75.2162],
         [75.3233, 75.4958, 75.8027, 75.4763, 75.6043]],

        [[75.2533, 75.2842, 75.3764, 75.3935, 75.5554],
         [75.8702, 75.4829, 75.8749, 75.8129, 75.8346],
         [75.5814, 75.4981, 75.2787, 75.9642, 75.1297],
         [75.6662, 75.4263, 75.1719, 75.1085, 75.0616],
         [75.0078, 75.9327, 75.4794, 75.4358, 75.0212],
         [75.2317, 75.6685, 75.2540, 75.4024, 75.8379]],

        [[75.1574, 75.5807, 75.6516, 75.2220, 75.3137],
         [75.3600, 75.9463, 75.8805, 75.3241, 75.1056],
         [75.5343, 75.0464, 75.4494, 75.8870, 75.4255],
         [75.5233, 75.9512, 75.7017, 75.7146, 75.9212],
         [75.5669, 75.3978, 75.3806, 75.3368, 75.1979],
         [75.8415, 75.7021, 75.7653, 75.6673

# Tensor Views

In [42]:
tensor1.shape

torch.Size([4, 6, 5])

In [43]:
tensor1.view([4,5,6])

tensor([[[75.8078, 75.6459, 75.3772, 75.8512, 75.5188, 75.0143],
         [75.6283, 75.9982, 75.1297, 75.7579, 75.6436, 75.5130],
         [75.4084, 75.5411, 75.8792, 75.8894, 75.9791, 75.9876],
         [75.0925, 75.1862, 75.6401, 75.3695, 75.7914, 75.8740],
         [75.2162, 75.3233, 75.4958, 75.8027, 75.4763, 75.6043]],

        [[75.2533, 75.2842, 75.3764, 75.3935, 75.5554, 75.8702],
         [75.4829, 75.8749, 75.8129, 75.8346, 75.5814, 75.4981],
         [75.2787, 75.9642, 75.1297, 75.6662, 75.4263, 75.1719],
         [75.1085, 75.0616, 75.0078, 75.9327, 75.4794, 75.4358],
         [75.0212, 75.2317, 75.6685, 75.2540, 75.4024, 75.8379]],

        [[75.1574, 75.5807, 75.6516, 75.2220, 75.3137, 75.3600],
         [75.9463, 75.8805, 75.3241, 75.1056, 75.5343, 75.0464],
         [75.4494, 75.8870, 75.4255, 75.5233, 75.9512, 75.7017],
         [75.7146, 75.9212, 75.5669, 75.3978, 75.3806, 75.3368],
         [75.1979, 75.8415, 75.7021, 75.7653, 75.6673, 75.0051]],

        [[75.0378, 

In [44]:
tensor1.shape

torch.Size([4, 6, 5])

# Gradient Descent

In [45]:
xg = torch.ones((5,2),requires_grad =True)

In [46]:
xg.requires_grad

True

In [47]:
xg

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [48]:
layer1 = xg + 2

In [49]:
layer1

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [50]:
layer2 = layer1 * 2

In [51]:
layer2

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>)

In [52]:
layer3 = layer2.mean()

In [53]:
layer3

tensor(6., grad_fn=<MeanBackward0>)

In [54]:
#deactivate

layer2_detach = layer2.detach()

In [55]:
layer2_detach

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]])

In [56]:
layer2_detach.mean()

tensor(6.)

# Sample Model

In [57]:
import torch

In [58]:
x = torch.tensor(([1,2,3,4]),dtype = torch.float32)
y = torch.tensor(([2,4,6,8]),dtype = torch.float32)

In [59]:
def forward(x,w):
  return w * x

In [60]:
def loss(y,y_pred):
  return ((y_pred - y)** 2).mean()

In [61]:
def gradient(x , y , y_pred):
  return ((2.0 * x) * (y_pred - y)).mean()

In [62]:
w = 0.0
n_iters = 25
learning_rate = 0.1

In [63]:
for epoch in range(n_iters):
  #Forward
  y_pred = forward(x,w)

  #loss
  l = loss(y , y_pred)

  #gradient
  grad = gradient(x , y ,y_pred)

  print(f"Epoch:{epoch+1} , Pred =: {y_pred.detach()} ,Grad :{grad.item()}, W: {w:4f} , Loss: {l:5f}")

  w -= learning_rate * grad

Epoch:1 , Pred =: tensor([0., 0., 0., 0.]) ,Grad :-30.0, W: 0.000000 , Loss: 30.000000
Epoch:2 , Pred =: tensor([ 3.,  6.,  9., 12.]) ,Grad :15.0, W: 3.000000 , Loss: 7.500000
Epoch:3 , Pred =: tensor([1.5000, 3.0000, 4.5000, 6.0000]) ,Grad :-7.5, W: 1.500000 , Loss: 1.875000
Epoch:4 , Pred =: tensor([2.2500, 4.5000, 6.7500, 9.0000]) ,Grad :3.75, W: 2.250000 , Loss: 0.468750
Epoch:5 , Pred =: tensor([1.8750, 3.7500, 5.6250, 7.5000]) ,Grad :-1.875, W: 1.875000 , Loss: 0.117188
Epoch:6 , Pred =: tensor([2.0625, 4.1250, 6.1875, 8.2500]) ,Grad :0.9375, W: 2.062500 , Loss: 0.029297
Epoch:7 , Pred =: tensor([1.9688, 3.9375, 5.9062, 7.8750]) ,Grad :-0.46875, W: 1.968750 , Loss: 0.007324
Epoch:8 , Pred =: tensor([2.0156, 4.0312, 6.0469, 8.0625]) ,Grad :0.234375, W: 2.015625 , Loss: 0.001831
Epoch:9 , Pred =: tensor([1.9922, 3.9844, 5.9766, 7.9688]) ,Grad :-0.1171875, W: 1.992188 , Loss: 0.000458
Epoch:10 , Pred =: tensor([2.0039, 4.0078, 6.0117, 8.0156]) ,Grad :0.05859375, W: 2.003906 , Loss: 

In [64]:
def forward(x,w):
  return w * x

In [65]:
def loss(y,y_pred):
  return ((y_pred - y)** 2).mean()

In [66]:
w = torch.tensor(0.0, requires_grad=True)
n_iters = 25
learning_rate = 0.1

In [67]:
# Model 2
import torch


for epoch in range(n_iters):
  #forward
  y_pred = forward(x,w)

  #Loss
  l = loss(y,y_pred)

  #Backpropagation

  l.backward()
  print(f"Epoch:{epoch+1} , Pred =: {y_pred.detach()} ,Grad :{w.grad.item():4f}, W: {w:4f} , Loss: {l:5f}")


  #weight update

  with torch.no_grad():
    w -= learning_rate * w.grad

  w.grad.zero_()

Epoch:1 , Pred =: tensor([0., 0., 0., 0.]) ,Grad :-30.000000, W: 0.000000 , Loss: 30.000000
Epoch:2 , Pred =: tensor([ 3.,  6.,  9., 12.]) ,Grad :15.000000, W: 3.000000 , Loss: 7.500000
Epoch:3 , Pred =: tensor([1.5000, 3.0000, 4.5000, 6.0000]) ,Grad :-7.500000, W: 1.500000 , Loss: 1.875000
Epoch:4 , Pred =: tensor([2.2500, 4.5000, 6.7500, 9.0000]) ,Grad :3.750000, W: 2.250000 , Loss: 0.468750
Epoch:5 , Pred =: tensor([1.8750, 3.7500, 5.6250, 7.5000]) ,Grad :-1.875000, W: 1.875000 , Loss: 0.117188
Epoch:6 , Pred =: tensor([2.0625, 4.1250, 6.1875, 8.2500]) ,Grad :0.937500, W: 2.062500 , Loss: 0.029297
Epoch:7 , Pred =: tensor([1.9688, 3.9375, 5.9062, 7.8750]) ,Grad :-0.468750, W: 1.968750 , Loss: 0.007324
Epoch:8 , Pred =: tensor([2.0156, 4.0312, 6.0469, 8.0625]) ,Grad :0.234375, W: 2.015625 , Loss: 0.001831
Epoch:9 , Pred =: tensor([1.9922, 3.9844, 5.9766, 7.9688]) ,Grad :-0.117188, W: 1.992188 , Loss: 0.000458
Epoch:10 , Pred =: tensor([2.0039, 4.0078, 6.0117, 8.0156]) ,Grad :0.058594

In [68]:
#Model 3

import torch.optim as optim

def forward(x,w):
  return w * x

w = torch.tensor(0.0, requires_grad=True)
optimizer = optim.SGD([w],lr = 0.1)
criterion = torch.nn.MSELoss()
n_iters = 30


for epoch in range(n_iters):
  #forward
  y_pred = forward(x,w)

  #Loss
  loss = criterion(y,y_pred)
  print(f"Epoch:{epoch+1},Pred: {y_pred.detach()},W:{w.item():4f},Loss:{loss.item():4f}")

  #Backward pass
  loss.backward()


  #weight update
  optimizer.step()

  #Zero Gradients
  optimizer.zero_grad()


Epoch:1,Pred: tensor([0., 0., 0., 0.]),W:0.000000,Loss:30.000000
Epoch:2,Pred: tensor([ 3.,  6.,  9., 12.]),W:3.000000,Loss:7.500000
Epoch:3,Pred: tensor([1.5000, 3.0000, 4.5000, 6.0000]),W:1.500000,Loss:1.875000
Epoch:4,Pred: tensor([2.2500, 4.5000, 6.7500, 9.0000]),W:2.250000,Loss:0.468750
Epoch:5,Pred: tensor([1.8750, 3.7500, 5.6250, 7.5000]),W:1.875000,Loss:0.117188
Epoch:6,Pred: tensor([2.0625, 4.1250, 6.1875, 8.2500]),W:2.062500,Loss:0.029297
Epoch:7,Pred: tensor([1.9688, 3.9375, 5.9062, 7.8750]),W:1.968750,Loss:0.007324
Epoch:8,Pred: tensor([2.0156, 4.0312, 6.0469, 8.0625]),W:2.015625,Loss:0.001831
Epoch:9,Pred: tensor([1.9922, 3.9844, 5.9766, 7.9688]),W:1.992188,Loss:0.000458
Epoch:10,Pred: tensor([2.0039, 4.0078, 6.0117, 8.0156]),W:2.003906,Loss:0.000114
Epoch:11,Pred: tensor([1.9980, 3.9961, 5.9941, 7.9922]),W:1.998047,Loss:0.000029
Epoch:12,Pred: tensor([2.0010, 4.0020, 6.0029, 8.0039]),W:2.000977,Loss:0.000007
Epoch:13,Pred: tensor([1.9995, 3.9990, 5.9985, 7.9980]),W:1.9995

# Neural Network

In [69]:
import torch
import torch.nn as nn

In [70]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super().sequential = nn.Sequential(
       nn.Flatten(),
       nn.Linear(784,512),
       nn.ReLU(),
       nn.Linear(512,512),
       nn.ReLU(),
       nn.Linear(512,10)

    )
    def forward(self , x):
      logits = self.sequential(x)
      return logits


In [71]:
input_image = torch.rand(3,28,28)
print(input_image,input_image.shape)
flatten = nn.Flatten()
flat_img = flatten(input_image)
print(flat_img,flat_img.shape)

tensor([[[0.5243, 0.8782, 0.8409,  ..., 0.0692, 0.8908, 0.2861],
         [0.0752, 0.0567, 0.5607,  ..., 0.2181, 0.7945, 0.7605],
         [0.0674, 0.0368, 0.1899,  ..., 0.9606, 0.6147, 0.5201],
         ...,
         [0.3831, 0.0029, 0.6173,  ..., 0.4608, 0.1930, 0.0246],
         [0.5912, 0.2636, 0.7683,  ..., 0.4246, 0.7874, 0.2012],
         [0.1961, 0.6354, 0.5451,  ..., 0.4633, 0.6238, 0.3952]],

        [[0.9731, 0.6224, 0.2647,  ..., 0.8186, 0.7240, 0.5203],
         [0.9177, 0.4801, 0.3433,  ..., 0.4072, 0.0475, 0.3674],
         [0.2561, 0.6405, 0.7593,  ..., 0.7520, 0.8931, 0.7894],
         ...,
         [0.3395, 0.3899, 0.9393,  ..., 0.6315, 0.1488, 0.4119],
         [0.3616, 0.2958, 0.9732,  ..., 0.9912, 0.6023, 0.6463],
         [0.0621, 0.5710, 0.0577,  ..., 0.6153, 0.3334, 0.7514]],

        [[0.6372, 0.4128, 0.6699,  ..., 0.5627, 0.3784, 0.3119],
         [0.0789, 0.3932, 0.0738,  ..., 0.3497, 0.5735, 0.6379],
         [0.2127, 0.7788, 0.6943,  ..., 0.7260, 0.0104, 0.

In [74]:
linear = nn.Linear(in_features=784,out_features=20)
linear_out = linear(flat_img)
print(linear_out,linear_out.shape)

tensor([[ 0.0603,  0.0528,  0.0101, -0.2277, -0.2462,  0.1684,  0.1020, -0.1312,
          0.1460, -0.3430, -0.0277,  0.6711,  0.1489, -0.5219,  0.2843,  0.1186,
          0.1508,  0.0482, -0.0603,  0.3479],
        [-0.0670,  0.1040, -0.3025,  0.0129, -0.0560, -0.1873,  0.2886,  0.2474,
          0.0223, -0.4869,  0.1257,  0.4115,  0.2337, -0.5621,  0.2523,  0.0352,
         -0.1010,  0.2975, -0.1116, -0.0484],
        [-0.0093,  0.2300, -0.1006, -0.1386,  0.1621,  0.3427,  0.1461,  0.3551,
         -0.1620, -0.2146, -0.1627,  0.1766,  0.0341, -0.7330,  0.1513,  0.1523,
         -0.1313,  0.4481, -0.0445,  0.4130]], grad_fn=<AddmmBackward0>) torch.Size([3, 20])


In [75]:
relu = nn.ReLU()
relu_out = relu(linear_out)
print(relu_out,relu_out.shape)

tensor([[0.0603, 0.0528, 0.0101, 0.0000, 0.0000, 0.1684, 0.1020, 0.0000, 0.1460,
         0.0000, 0.0000, 0.6711, 0.1489, 0.0000, 0.2843, 0.1186, 0.1508, 0.0482,
         0.0000, 0.3479],
        [0.0000, 0.1040, 0.0000, 0.0129, 0.0000, 0.0000, 0.2886, 0.2474, 0.0223,
         0.0000, 0.1257, 0.4115, 0.2337, 0.0000, 0.2523, 0.0352, 0.0000, 0.2975,
         0.0000, 0.0000],
        [0.0000, 0.2300, 0.0000, 0.0000, 0.1621, 0.3427, 0.1461, 0.3551, 0.0000,
         0.0000, 0.0000, 0.1766, 0.0341, 0.0000, 0.1513, 0.1523, 0.0000, 0.4481,
         0.0000, 0.4130]], grad_fn=<ReluBackward0>) torch.Size([3, 20])
