<a href="https://colab.research.google.com/github/Mahdi-Miri/Pytorch-Tutorial/blob/main/Pytorch-Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision -U

In [2]:
import torch

print(torch.__version__)

2.5.1+cu121


In [3]:
data = [[1,2],[3,4],[5,6]]

In [4]:
data

[[1, 2], [3, 4], [5, 6]]

In [5]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
x = torch.zeros((3,3,5),dtype=torch.float16)

In [7]:
x

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16)

In [8]:
x[1]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [9]:
shape = (2,3,4)

In [10]:
x = torch.ones(shape)

In [11]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
x = torch.rand(shape)

In [13]:
x

tensor([[[0.4373, 0.2252, 0.7449, 0.2436],
         [0.4758, 0.7797, 0.8093, 0.3571],
         [0.6610, 0.1719, 0.8228, 0.6628]],

        [[0.6148, 0.5797, 0.0683, 0.8349],
         [0.1222, 0.7913, 0.4300, 0.7530],
         [0.8303, 0.8769, 0.4540, 0.1202]]])

In [14]:
x = torch.tensor(([1,2,3,4,5],[5,4,3,2,1]))

In [15]:
x

tensor([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]])

In [16]:
x *2

tensor([[ 2,  4,  6,  8, 10],
        [10,  8,  6,  4,  2]])

In [17]:
x.shape

torch.Size([2, 5])

In [18]:
x.dtype

torch.int64

In [19]:
x.device

device(type='cpu')

In [20]:
x[0]

tensor([1, 2, 3, 4, 5])

In [21]:
x[ : ,  0]

tensor([1, 5])

In [22]:
x[...,-1]

tensor([5, 1])

# Joining Tensors

In [23]:
shape1 = (4,6,5)
shape2 = (4,5,6)

In [24]:
tensor1  = torch.rand(shape1)

In [25]:
tensor2 = torch.rand(shape2)

In [26]:
print("Tensor 1 :")
tensor1

Tensor 1 :


tensor([[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

        [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
         [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
         [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
         [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
         [0.4492, 0.4530, 0.8074, 0.1143, 0.2235]],

        [[0.9087, 0.9437, 0.8327, 0.0235, 0.8607],
         [0.6586, 0.4641, 0.9316, 0.8648, 0.0161],
         [0.8251, 0.6128, 0.1418, 0.7170, 0.2898],
         [0.9667, 0.6574, 0.6895, 0.5212, 0.6519],
         [0.7115, 0.6377, 0.2840, 0.3516, 0.1787],
         [0.9410, 0.3886, 0.9329, 0.7445, 0.8816]],

        [[0.6784, 0.7717, 0.3923, 0.3438, 0.6364],
         [0.8236, 0.8191,

In [27]:
print("Tensor 2 :")
tensor2

Tensor 2 :


tensor([[[0.2500, 0.3182, 0.5976, 0.4803, 0.8020, 0.4726],
         [0.2817, 0.0784, 0.9425, 0.8108, 0.0179, 0.2015],
         [0.8662, 0.0322, 0.1788, 0.1376, 0.6883, 0.0753],
         [0.5763, 0.0395, 0.1853, 0.0430, 0.7992, 0.6066],
         [0.9913, 0.1268, 0.9789, 0.5080, 0.4388, 0.6636]],

        [[0.7203, 0.9517, 0.1933, 0.4458, 0.9949, 0.8223],
         [0.1124, 0.3660, 0.2767, 0.1421, 0.6202, 0.9532],
         [0.3064, 0.6224, 0.1080, 0.0979, 0.4268, 0.2933],
         [0.2337, 0.4028, 0.5698, 0.3846, 0.7026, 0.7327],
         [0.0659, 0.7590, 0.5472, 0.1168, 0.1225, 0.2068]],

        [[0.8044, 0.3401, 0.1149, 0.6363, 0.2176, 0.2857],
         [0.2954, 0.7595, 0.0978, 0.8775, 0.1331, 0.0464],
         [0.8423, 0.8341, 0.5874, 0.6119, 0.4488, 0.9906],
         [0.0857, 0.2834, 0.6257, 0.7608, 0.6215, 0.9114],
         [0.2732, 0.1894, 0.0455, 0.2417, 0.4901, 0.1443]],

        [[0.7588, 0.9583, 0.2283, 0.2388, 0.5987, 0.8709],
         [0.3697, 0.2751, 0.9858, 0.4918, 0.8036, 

In [28]:
t1 = torch.cat([tensor1,tensor1],dim =1)

In [29]:
t1

tensor([[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849],
         [0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

        [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
         [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
         [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
         [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
         [0.4492, 0.4530, 0.8074, 0.1143, 0.2235],
         [0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4

In [30]:
t1 = torch.cat([tensor1,tensor1],dim =0)

In [31]:
t1

tensor([[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

        [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
         [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
         [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
         [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
         [0.4492, 0.4530, 0.8074, 0.1143, 0.2235]],

        [[0.9087, 0.9437, 0.8327, 0.0235, 0.8607],
         [0.6586, 0.4641, 0.9316, 0.8648, 0.0161],
         [0.8251, 0.6128, 0.1418, 0.7170, 0.2898],
         [0.9667, 0.6574, 0.6895, 0.5212, 0.6519],
         [0.7115, 0.6377, 0.2840, 0.3516, 0.1787],
         [0.9410, 0.3886, 0.9329, 0.7445, 0.8816]],

        [[0.6784, 0.7717, 0.3923, 0.3438, 0.6364],
         [0.8236, 0.8191,

In [32]:
t1 = torch.stack([tensor1,tensor1])

In [33]:
t1

tensor([[[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
          [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
          [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
          [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
          [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
          [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

         [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
          [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
          [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
          [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
          [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
          [0.4492, 0.4530, 0.8074, 0.1143, 0.2235]],

         [[0.9087, 0.9437, 0.8327, 0.0235, 0.8607],
          [0.6586, 0.4641, 0.9316, 0.8648, 0.0161],
          [0.8251, 0.6128, 0.1418, 0.7170, 0.2898],
          [0.9667, 0.6574, 0.6895, 0.5212, 0.6519],
          [0.7115, 0.6377, 0.2840, 0.3516, 0.1787],
          [0.9410, 0.3886, 0.9329, 0.7445, 0.8816]],

         [[0.6784, 0.7717, 0.3923, 0.3438, 0.6364],
      

In [34]:
tensor1 @ tensor2

tensor([[[2.2079, 0.4852, 2.3949, 1.6537, 1.9270, 1.5268],
         [2.0966, 0.3927, 1.6908, 1.0938, 1.8214, 1.1714],
         [1.2697, 0.1862, 1.3895, 0.8851, 0.7242, 0.8129],
         [1.1996, 0.3987, 1.6437, 1.1940, 1.3123, 1.0600],
         [1.4970, 0.3032, 1.7188, 1.1897, 1.1546, 1.0085],
         [0.9590, 0.1884, 0.9330, 0.6178, 0.9963, 0.8132]],

        [[0.8675, 1.5720, 0.8481, 0.7095, 1.8458, 1.9334],
         [0.5618, 1.0323, 0.4169, 0.3869, 1.1192, 1.1958],
         [0.5359, 1.2158, 0.6753, 0.4358, 1.2557, 1.4085],
         [0.6616, 1.5185, 0.7876, 0.5032, 1.2883, 1.2963],
         [0.7928, 1.9338, 0.9539, 0.5812, 1.5022, 1.5621],
         [0.6633, 1.3115, 0.4868, 0.4137, 1.1801, 1.1680]],

        [[1.9484, 1.8901, 0.7397, 2.1418, 1.1334, 1.2738],
         [1.5302, 1.6017, 1.2102, 2.0583, 1.1685, 1.9230],
         [1.1049, 1.1224, 0.6999, 1.7652, 0.9124, 1.0999],
         [1.7755, 1.6745, 0.9363, 2.1681, 1.2507, 1.5588],
         [1.0790, 1.0967, 0.5391, 1.4968, 0.6733, 0.

In [35]:
tensor1.T

<ipython-input-35-0fee77ff0160>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  tensor1.T


tensor([[[0.8217, 0.5081, 0.9087, 0.6784],
         [0.7053, 0.4311, 0.6586, 0.8236],
         [0.0910, 0.1568, 0.8251, 0.1610],
         [0.8572, 0.2655, 0.9667, 0.7187],
         [0.4275, 0.4386, 0.7115, 0.9005],
         [0.2959, 0.4492, 0.9410, 0.9834]],

        [[0.8362, 0.7539, 0.9437, 0.7717],
         [0.1990, 0.6163, 0.4641, 0.8191],
         [0.4584, 0.7430, 0.6128, 0.2697],
         [0.6413, 0.3709, 0.6574, 0.2173],
         [0.6917, 0.5549, 0.6377, 0.2722],
         [0.3492, 0.4530, 0.3886, 0.4504]],

        [[0.6431, 0.7640, 0.8327, 0.3923],
         [0.9922, 0.4747, 0.9316, 0.3946],
         [0.2084, 0.7386, 0.1418, 0.7330],
         [0.1868, 0.9287, 0.6895, 0.4692],
         [0.3864, 0.9398, 0.2840, 0.1888],
         [0.1398, 0.8074, 0.9329, 0.0164]],

        [[0.5052, 0.7722, 0.0235, 0.3438],
         [0.2288, 0.1397, 0.8648, 0.5699],
         [0.1556, 0.4229, 0.7170, 0.6947],
         [0.3678, 0.4843, 0.5212, 0.1664],
         [0.2801, 0.3184, 0.3516, 0.9926],
     

In [36]:
tensor2 * tensor2

tensor([[[6.2497e-02, 1.0123e-01, 3.5713e-01, 2.3070e-01, 6.4323e-01,
          2.2338e-01],
         [7.9344e-02, 6.1537e-03, 8.8824e-01, 6.5746e-01, 3.2051e-04,
          4.0596e-02],
         [7.5037e-01, 1.0351e-03, 3.1966e-02, 1.8936e-02, 4.7376e-01,
          5.6770e-03],
         [3.3208e-01, 1.5611e-03, 3.4322e-02, 1.8491e-03, 6.3874e-01,
          3.6798e-01],
         [9.8277e-01, 1.6087e-02, 9.5828e-01, 2.5805e-01, 1.9255e-01,
          4.4043e-01]],

        [[5.1880e-01, 9.0567e-01, 3.7362e-02, 1.9874e-01, 9.8975e-01,
          6.7613e-01],
         [1.2637e-02, 1.3399e-01, 7.6558e-02, 2.0195e-02, 3.8465e-01,
          9.0866e-01],
         [9.3874e-02, 3.8732e-01, 1.1659e-02, 9.5825e-03, 1.8213e-01,
          8.6026e-02],
         [5.4603e-02, 1.6221e-01, 3.2470e-01, 1.4795e-01, 4.9359e-01,
          5.3688e-01],
         [4.3473e-03, 5.7603e-01, 2.9941e-01, 1.3632e-02, 1.5011e-02,
          4.2758e-02]],

        [[6.4712e-01, 1.1565e-01, 1.3208e-02, 4.0494e-01, 4.7344e-

In [37]:
tensor1 / 2

tensor([[[0.4108, 0.4181, 0.3215, 0.2526, 0.4634],
         [0.3527, 0.0995, 0.4961, 0.1144, 0.4403],
         [0.0455, 0.2292, 0.1042, 0.0778, 0.4275],
         [0.4286, 0.3207, 0.0934, 0.1839, 0.2173],
         [0.2138, 0.3459, 0.1932, 0.1400, 0.3526],
         [0.1479, 0.1746, 0.0699, 0.3325, 0.1424]],

        [[0.2540, 0.3770, 0.3820, 0.3861, 0.0172],
         [0.2156, 0.3082, 0.2374, 0.0699, 0.0294],
         [0.0784, 0.3715, 0.3693, 0.2114, 0.1084],
         [0.1327, 0.1855, 0.4643, 0.2421, 0.2352],
         [0.2193, 0.2775, 0.4699, 0.1592, 0.3953],
         [0.2246, 0.2265, 0.4037, 0.0572, 0.1118]],

        [[0.4543, 0.4719, 0.4163, 0.0117, 0.4303],
         [0.3293, 0.2321, 0.4658, 0.4324, 0.0081],
         [0.4126, 0.3064, 0.0709, 0.3585, 0.1449],
         [0.4834, 0.3287, 0.3448, 0.2606, 0.3260],
         [0.3557, 0.3188, 0.1420, 0.1758, 0.0894],
         [0.4705, 0.1943, 0.4665, 0.3722, 0.4408]],

        [[0.3392, 0.3859, 0.1961, 0.1719, 0.3182],
         [0.4118, 0.4095,

# Getting Value Of Single-Element Tensor

In [38]:
tensor1

tensor([[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

        [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
         [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
         [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
         [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
         [0.4492, 0.4530, 0.8074, 0.1143, 0.2235]],

        [[0.9087, 0.9437, 0.8327, 0.0235, 0.8607],
         [0.6586, 0.4641, 0.9316, 0.8648, 0.0161],
         [0.8251, 0.6128, 0.1418, 0.7170, 0.2898],
         [0.9667, 0.6574, 0.6895, 0.5212, 0.6519],
         [0.7115, 0.6377, 0.2840, 0.3516, 0.1787],
         [0.9410, 0.3886, 0.9329, 0.7445, 0.8816]],

        [[0.6784, 0.7717, 0.3923, 0.3438, 0.6364],
         [0.8236, 0.8191,

In [39]:
tensor1[0,1,2].item()

0.9921546578407288

# Inplace Operation

In [40]:
tensor1

tensor([[[0.8217, 0.8362, 0.6431, 0.5052, 0.9268],
         [0.7053, 0.1990, 0.9922, 0.2288, 0.8806],
         [0.0910, 0.4584, 0.2084, 0.1556, 0.8550],
         [0.8572, 0.6413, 0.1868, 0.3678, 0.4346],
         [0.4275, 0.6917, 0.3864, 0.2801, 0.7053],
         [0.2959, 0.3492, 0.1398, 0.6650, 0.2849]],

        [[0.5081, 0.7539, 0.7640, 0.7722, 0.0343],
         [0.4311, 0.6163, 0.4747, 0.1397, 0.0588],
         [0.1568, 0.7430, 0.7386, 0.4229, 0.2168],
         [0.2655, 0.3709, 0.9287, 0.4843, 0.4704],
         [0.4386, 0.5549, 0.9398, 0.3184, 0.7906],
         [0.4492, 0.4530, 0.8074, 0.1143, 0.2235]],

        [[0.9087, 0.9437, 0.8327, 0.0235, 0.8607],
         [0.6586, 0.4641, 0.9316, 0.8648, 0.0161],
         [0.8251, 0.6128, 0.1418, 0.7170, 0.2898],
         [0.9667, 0.6574, 0.6895, 0.5212, 0.6519],
         [0.7115, 0.6377, 0.2840, 0.3516, 0.1787],
         [0.9410, 0.3886, 0.9329, 0.7445, 0.8816]],

        [[0.6784, 0.7717, 0.3923, 0.3438, 0.6364],
         [0.8236, 0.8191,

In [41]:
tensor1.add_(75)

tensor([[[75.8217, 75.8362, 75.6431, 75.5052, 75.9268],
         [75.7053, 75.1990, 75.9922, 75.2288, 75.8806],
         [75.0910, 75.4584, 75.2084, 75.1556, 75.8550],
         [75.8572, 75.6413, 75.1868, 75.3678, 75.4346],
         [75.4275, 75.6917, 75.3864, 75.2801, 75.7053],
         [75.2959, 75.3492, 75.1398, 75.6650, 75.2849]],

        [[75.5080, 75.7539, 75.7640, 75.7722, 75.0343],
         [75.4311, 75.6163, 75.4747, 75.1397, 75.0588],
         [75.1568, 75.7430, 75.7386, 75.4229, 75.2168],
         [75.2655, 75.3709, 75.9287, 75.4843, 75.4704],
         [75.4386, 75.5549, 75.9398, 75.3184, 75.7906],
         [75.4492, 75.4530, 75.8074, 75.1143, 75.2235]],

        [[75.9087, 75.9437, 75.8327, 75.0235, 75.8607],
         [75.6586, 75.4641, 75.9316, 75.8648, 75.0161],
         [75.8251, 75.6128, 75.1418, 75.7170, 75.2898],
         [75.9667, 75.6574, 75.6895, 75.5212, 75.6519],
         [75.7115, 75.6377, 75.2840, 75.3516, 75.1787],
         [75.9410, 75.3886, 75.9329, 75.7445

# Tensor Views

In [42]:
tensor1.shape

torch.Size([4, 6, 5])

In [43]:
tensor1.view([4,5,6])

tensor([[[75.8217, 75.8362, 75.6431, 75.5052, 75.9268, 75.7053],
         [75.1990, 75.9922, 75.2288, 75.8806, 75.0910, 75.4584],
         [75.2084, 75.1556, 75.8550, 75.8572, 75.6413, 75.1868],
         [75.3678, 75.4346, 75.4275, 75.6917, 75.3864, 75.2801],
         [75.7053, 75.2959, 75.3492, 75.1398, 75.6650, 75.2849]],

        [[75.5080, 75.7539, 75.7640, 75.7722, 75.0343, 75.4311],
         [75.6163, 75.4747, 75.1397, 75.0588, 75.1568, 75.7430],
         [75.7386, 75.4229, 75.2168, 75.2655, 75.3709, 75.9287],
         [75.4843, 75.4704, 75.4386, 75.5549, 75.9398, 75.3184],
         [75.7906, 75.4492, 75.4530, 75.8074, 75.1143, 75.2235]],

        [[75.9087, 75.9437, 75.8327, 75.0235, 75.8607, 75.6586],
         [75.4641, 75.9316, 75.8648, 75.0161, 75.8251, 75.6128],
         [75.1418, 75.7170, 75.2898, 75.9667, 75.6574, 75.6895],
         [75.5212, 75.6519, 75.7115, 75.6377, 75.2840, 75.3516],
         [75.1787, 75.9410, 75.3886, 75.9329, 75.7445, 75.8816]],

        [[75.6784, 

In [44]:
tensor1.shape

torch.Size([4, 6, 5])

# Gradient Descent

In [45]:
xg = torch.ones((5,2),requires_grad =True)

In [46]:
xg.requires_grad

True

In [47]:
xg

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [48]:
layer1 = xg + 2

In [49]:
layer1

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [50]:
layer2 = layer1 * 2

In [51]:
layer2

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>)

In [52]:
layer3 = layer2.mean()

In [53]:
layer3

tensor(6., grad_fn=<MeanBackward0>)

In [54]:
#deactivate

layer2_detach = layer2.detach()

In [55]:
layer2_detach

tensor([[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]])

In [56]:
layer2_detach.mean()

tensor(6.)

# Sample Model

In [57]:
import torch

In [58]:
x = torch.tensor(([1,2,3,4]),dtype = torch.float32)
y = torch.tensor(([2,4,6,8]),dtype = torch.float32)

In [59]:
def forward(x,w):
  return w * x

In [60]:
def loss(y,y_pred):
  return ((y_pred - y)** 2).mean()

In [61]:
def gradient(x , y , y_pred):
  return ((2.0 * x) * (y_pred - y)).mean()

In [62]:
w = 0.0
n_iters = 25
learning_rate = 0.1

In [63]:
for epoch in range(n_iters):
  #Forward
  y_pred = forward(x,w)

  #loss
  l = loss(y , y_pred)

  #gradient
  grad = gradient(x , y ,y_pred)

  print(f"Epoch:{epoch+1} , Pred =: {y_pred.detach()} ,Grad :{grad.item()}, W: {w:4f} , Loss: {l:5f}")

  w -= learning_rate * grad

Epoch:1 , Pred =: tensor([0., 0., 0., 0.]) ,Grad :-30.0, W: 0.000000 , Loss: 30.000000
Epoch:2 , Pred =: tensor([ 3.,  6.,  9., 12.]) ,Grad :15.0, W: 3.000000 , Loss: 7.500000
Epoch:3 , Pred =: tensor([1.5000, 3.0000, 4.5000, 6.0000]) ,Grad :-7.5, W: 1.500000 , Loss: 1.875000
Epoch:4 , Pred =: tensor([2.2500, 4.5000, 6.7500, 9.0000]) ,Grad :3.75, W: 2.250000 , Loss: 0.468750
Epoch:5 , Pred =: tensor([1.8750, 3.7500, 5.6250, 7.5000]) ,Grad :-1.875, W: 1.875000 , Loss: 0.117188
Epoch:6 , Pred =: tensor([2.0625, 4.1250, 6.1875, 8.2500]) ,Grad :0.9375, W: 2.062500 , Loss: 0.029297
Epoch:7 , Pred =: tensor([1.9688, 3.9375, 5.9062, 7.8750]) ,Grad :-0.46875, W: 1.968750 , Loss: 0.007324
Epoch:8 , Pred =: tensor([2.0156, 4.0312, 6.0469, 8.0625]) ,Grad :0.234375, W: 2.015625 , Loss: 0.001831
Epoch:9 , Pred =: tensor([1.9922, 3.9844, 5.9766, 7.9688]) ,Grad :-0.1171875, W: 1.992188 , Loss: 0.000458
Epoch:10 , Pred =: tensor([2.0039, 4.0078, 6.0117, 8.0156]) ,Grad :0.05859375, W: 2.003906 , Loss: 

In [64]:
def forward(x,w):
  return w * x

In [65]:
def loss(y,y_pred):
  return ((y_pred - y)** 2).mean()

In [66]:
w = torch.tensor(0.0, requires_grad=True)
n_iters = 25
learning_rate = 0.1

In [67]:
# Model 2
import torch


for epoch in range(n_iters):
  #forward
  y_pred = forward(x,w)

  #Loss
  l = loss(y,y_pred)

  #Backpropagation

  l.backward()
  print(f"Epoch:{epoch+1} , Pred =: {y_pred.detach()} ,Grad :{w.grad.item():4f}, W: {w:4f} , Loss: {l:5f}")


  #weight update

  with torch.no_grad():
    w -= learning_rate * w.grad

  w.grad.zero_()

Epoch:1 , Pred =: tensor([0., 0., 0., 0.]) ,Grad :-30.000000, W: 0.000000 , Loss: 30.000000
Epoch:2 , Pred =: tensor([ 3.,  6.,  9., 12.]) ,Grad :15.000000, W: 3.000000 , Loss: 7.500000
Epoch:3 , Pred =: tensor([1.5000, 3.0000, 4.5000, 6.0000]) ,Grad :-7.500000, W: 1.500000 , Loss: 1.875000
Epoch:4 , Pred =: tensor([2.2500, 4.5000, 6.7500, 9.0000]) ,Grad :3.750000, W: 2.250000 , Loss: 0.468750
Epoch:5 , Pred =: tensor([1.8750, 3.7500, 5.6250, 7.5000]) ,Grad :-1.875000, W: 1.875000 , Loss: 0.117188
Epoch:6 , Pred =: tensor([2.0625, 4.1250, 6.1875, 8.2500]) ,Grad :0.937500, W: 2.062500 , Loss: 0.029297
Epoch:7 , Pred =: tensor([1.9688, 3.9375, 5.9062, 7.8750]) ,Grad :-0.468750, W: 1.968750 , Loss: 0.007324
Epoch:8 , Pred =: tensor([2.0156, 4.0312, 6.0469, 8.0625]) ,Grad :0.234375, W: 2.015625 , Loss: 0.001831
Epoch:9 , Pred =: tensor([1.9922, 3.9844, 5.9766, 7.9688]) ,Grad :-0.117188, W: 1.992188 , Loss: 0.000458
Epoch:10 , Pred =: tensor([2.0039, 4.0078, 6.0117, 8.0156]) ,Grad :0.058594

In [68]:
#Model 3

import torch.optim as optim

def forward(x,w):
  return w * x

w = torch.tensor(0.0, requires_grad=True)
optimizer = optim.SGD([w],lr = 0.1)
criterion = torch.nn.MSELoss()
n_iters = 30


for epoch in range(n_iters):
  #forward
  y_pred = forward(x,w)

  #Loss
  loss = criterion(y,y_pred)
  print(f"Epoch:{epoch+1},Pred: {y_pred.detach()},W:{w.item():4f},Loss:{loss.item():4f}")

  #Backward pass
  loss.backward()


  #weight update
  optimizer.step()

  #Zero Gradients
  optimizer.zero_grad()


Epoch:1,Pred: tensor([0., 0., 0., 0.]),W:0.000000,Loss:30.000000
Epoch:2,Pred: tensor([ 3.,  6.,  9., 12.]),W:3.000000,Loss:7.500000
Epoch:3,Pred: tensor([1.5000, 3.0000, 4.5000, 6.0000]),W:1.500000,Loss:1.875000
Epoch:4,Pred: tensor([2.2500, 4.5000, 6.7500, 9.0000]),W:2.250000,Loss:0.468750
Epoch:5,Pred: tensor([1.8750, 3.7500, 5.6250, 7.5000]),W:1.875000,Loss:0.117188
Epoch:6,Pred: tensor([2.0625, 4.1250, 6.1875, 8.2500]),W:2.062500,Loss:0.029297
Epoch:7,Pred: tensor([1.9688, 3.9375, 5.9062, 7.8750]),W:1.968750,Loss:0.007324
Epoch:8,Pred: tensor([2.0156, 4.0312, 6.0469, 8.0625]),W:2.015625,Loss:0.001831
Epoch:9,Pred: tensor([1.9922, 3.9844, 5.9766, 7.9688]),W:1.992188,Loss:0.000458
Epoch:10,Pred: tensor([2.0039, 4.0078, 6.0117, 8.0156]),W:2.003906,Loss:0.000114
Epoch:11,Pred: tensor([1.9980, 3.9961, 5.9941, 7.9922]),W:1.998047,Loss:0.000029
Epoch:12,Pred: tensor([2.0010, 4.0020, 6.0029, 8.0039]),W:2.000977,Loss:0.000007
Epoch:13,Pred: tensor([1.9995, 3.9990, 5.9985, 7.9980]),W:1.9995

# Neural Network

In [69]:
import torch
import torch.nn as nn

In [70]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super().sequential = nn.Sequential(
       nn.Flatten(),
       nn.Linear(784,512),
       nn.ReLU(),
       nn.Linear(512,512),
       nn.ReLU(),
       nn.Linear(512,10)

    )
    def forward(self , x):
      logits = self.sequential(x)
      return logits


In [71]:
input_image = torch.rand(3,28,28)
print(input_image,input_image.shape)
flatten = nn.Flatten()
flat_img = flatten(input_image)
print(flat_img,flat_img.shape)

tensor([[[0.8020, 0.4772, 0.7308,  ..., 0.2437, 0.4667, 0.1212],
         [0.6757, 0.7143, 0.2525,  ..., 0.6304, 0.0318, 0.2116],
         [0.7393, 0.8340, 0.9508,  ..., 0.0599, 0.9207, 0.2018],
         ...,
         [0.3591, 0.6192, 0.8849,  ..., 0.6927, 0.9217, 0.6087],
         [0.7488, 0.3866, 0.7255,  ..., 0.8679, 0.9195, 0.6768],
         [0.3201, 0.7056, 0.1240,  ..., 0.7113, 0.5594, 0.6380]],

        [[0.2932, 0.1847, 0.9160,  ..., 0.0813, 0.1221, 0.7803],
         [0.4460, 0.0139, 0.3254,  ..., 0.3733, 0.1068, 0.6074],
         [0.9208, 0.2063, 0.3651,  ..., 0.7639, 0.4417, 0.3031],
         ...,
         [0.6696, 0.2613, 0.9849,  ..., 0.2416, 0.9523, 0.4608],
         [0.0435, 0.4863, 0.0015,  ..., 0.3926, 0.0592, 0.3308],
         [0.4888, 0.5610, 0.4372,  ..., 0.7819, 0.7497, 0.8092]],

        [[0.8204, 0.7876, 0.7129,  ..., 0.9131, 0.6155, 0.3209],
         [0.6125, 0.6668, 0.3341,  ..., 0.3044, 0.0756, 0.4150],
         [0.2212, 0.7341, 0.6597,  ..., 0.8378, 0.9808, 0.

In [72]:
linear = nn.Linear(in_features=784,out_features=20)
linear_out = linear(flat_img)
print(linear_out,linear_out.shape)

tensor([[ 0.3107,  0.0170, -0.3187,  0.1716, -0.3308, -0.4667, -0.0595,  0.0509,
         -0.1257,  0.1176,  0.1413, -0.6692,  0.1438, -0.6096, -0.5850, -0.2413,
         -0.1129,  0.0494,  0.0733,  0.0360],
        [ 0.3643,  0.3615, -0.0176,  0.1068, -0.3167, -0.0594, -0.1023,  0.4669,
         -0.4168,  0.0332,  0.6170, -0.0395, -0.1629, -0.4202, -0.4273, -0.1672,
         -0.0385, -0.1274,  0.2937, -0.0228],
        [ 0.2979,  0.4737, -0.1535,  0.2396, -0.2879, -0.3657,  0.1297,  0.3963,
         -0.1195,  0.6016,  0.4643, -0.5758, -0.2646, -0.2722, -0.3222, -0.2998,
         -0.1440,  0.2117,  0.2955,  0.2600]], grad_fn=<AddmmBackward0>) torch.Size([3, 20])


In [73]:
relu = nn.ReLU()
relu_out = relu(linear_out)
print(relu_out,relu_out.shape)

tensor([[0.3107, 0.0170, 0.0000, 0.1716, 0.0000, 0.0000, 0.0000, 0.0509, 0.0000,
         0.1176, 0.1413, 0.0000, 0.1438, 0.0000, 0.0000, 0.0000, 0.0000, 0.0494,
         0.0733, 0.0360],
        [0.3643, 0.3615, 0.0000, 0.1068, 0.0000, 0.0000, 0.0000, 0.4669, 0.0000,
         0.0332, 0.6170, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.2937, 0.0000],
        [0.2979, 0.4737, 0.0000, 0.2396, 0.0000, 0.0000, 0.1297, 0.3963, 0.0000,
         0.6016, 0.4643, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2117,
         0.2955, 0.2600]], grad_fn=<ReluBackward0>) torch.Size([3, 20])


In [74]:
linear2 = nn.Linear(in_features=20 , out_features = 10)
logits = linear2(relu_out)
logits

tensor([[ 0.1715,  0.2310,  0.1044,  0.1739, -0.0318, -0.2023,  0.0528, -0.0787,
         -0.0924, -0.0066],
        [ 0.3190,  0.2400,  0.0435,  0.0480,  0.0143, -0.0701,  0.1156, -0.0505,
         -0.0839,  0.0837],
        [ 0.2406,  0.2993,  0.1586,  0.1380, -0.0247, -0.1504,  0.1027,  0.0900,
          0.0965,  0.0439]], grad_fn=<AddmmBackward0>)

# Linear Regression

In [75]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

In [77]:
x_numpy,y_numpy = datasets.make_regression(n_samples = 100, noise = 20,random_state=1,n_features=1)

In [82]:
X = torch.from_numpy(x_numpy.astype(np.float32))
X.shape

torch.Size([100, 1])

In [83]:
Y = torch.from_numpy(y_numpy.astype(np.float32))
Y.shape

torch.Size([100])

In [90]:
y = Y.view(Y.shape[0],1)
print(f"Y:{y.shape}")

Y:torch.Size([100, 1])
