<a href="https://colab.research.google.com/github/Mahdi-Miri/Pytorch-Tutorial/blob/main/Pytorch-Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision -U

In [2]:
import torch

print(torch.__version__)

2.5.1+cu121


In [3]:
data = [[1,2],[3,4],[5,6]]

In [4]:
data

[[1, 2], [3, 4], [5, 6]]

In [5]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
x = torch.zeros((3,3,5),dtype=torch.float16)

In [18]:
x

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16)

In [19]:
x[1]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [21]:
shape = (2,3,4)

In [22]:
x = torch.ones(shape)

In [23]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [24]:
x = torch.rand(shape)

In [25]:
x

tensor([[[0.4614, 0.4813, 0.6929, 0.5494],
         [0.6891, 0.7991, 0.3800, 0.7510],
         [0.8111, 0.2988, 0.5639, 0.3903]],

        [[0.1577, 0.3950, 0.7497, 0.0530],
         [0.7528, 0.5905, 0.0059, 0.4633],
         [0.7369, 0.4175, 0.0592, 0.6505]]])

In [34]:
x = torch.tensor(([1,2,3,4,5],[5,4,3,2,1]))

In [35]:
x

tensor([[1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1]])

In [36]:
x *2

tensor([[ 2,  4,  6,  8, 10],
        [10,  8,  6,  4,  2]])

In [37]:
x.shape

torch.Size([2, 5])

In [38]:
x.dtype

torch.int64

In [39]:
x.device

device(type='cpu')

In [40]:
x[0]

tensor([1, 2, 3, 4, 5])

In [42]:
x[ : ,  0]

tensor([1, 5])

In [44]:
x[...,-1]

tensor([5, 1])

# Joining Tensors

In [51]:
shape1 = (4,6,5)
shape2 = (4,5,6)

In [52]:
tensor1  = torch.rand(shape1)

In [53]:
tensor2 = torch.rand(shape2)

In [57]:
print("Tensor 1 :")
tensor1

Tensor 1 :


tensor([[[0.5046, 0.6684, 0.0238, 0.0734, 0.4376],
         [0.3345, 0.2217, 0.1588, 0.4637, 0.8703],
         [0.8007, 0.6400, 0.2294, 0.1902, 0.2603],
         [0.0829, 0.1971, 0.3112, 0.8721, 0.3244],
         [0.6329, 0.2105, 0.7397, 0.7108, 0.9076],
         [0.2056, 0.8665, 0.4776, 0.5808, 0.6268]],

        [[0.7440, 0.1100, 0.5665, 0.2272, 0.3090],
         [0.1998, 0.5057, 0.7349, 0.3224, 0.3077],
         [0.0484, 0.2798, 0.8076, 0.8538, 0.5174],
         [0.4101, 0.4949, 0.8750, 0.0775, 0.0864],
         [0.8816, 0.5973, 0.3059, 0.3990, 0.0769],
         [0.0047, 0.1007, 0.6146, 0.5630, 0.5695]],

        [[0.3703, 0.8050, 0.5403, 0.1085, 0.6040],
         [0.8221, 0.0058, 0.5775, 0.1665, 0.2900],
         [0.5516, 0.9394, 0.5325, 0.4447, 0.0666],
         [0.1007, 0.9527, 0.0646, 0.2111, 0.8109],
         [0.8386, 0.3704, 0.8307, 0.2947, 0.3106],
         [0.2516, 0.9790, 0.0042, 0.1317, 0.6959]],

        [[0.6884, 0.4396, 0.4156, 0.4487, 0.2442],
         [0.0051, 0.7431,

In [58]:
print("Tensor 2 :")
tensor2

Tensor 2 :


tensor([[[0.2532, 0.9074, 0.7224, 0.6578, 0.4000, 0.5056],
         [0.3073, 0.5684, 0.8624, 0.4057, 0.6747, 0.6294],
         [0.1236, 0.5976, 0.4644, 0.5771, 0.1180, 0.9368],
         [0.9834, 0.5037, 0.0676, 0.2596, 0.6695, 0.9026],
         [0.7167, 0.0587, 0.5228, 0.8458, 0.7318, 0.5651]],

        [[0.4670, 0.2143, 0.9459, 0.7454, 0.3198, 0.6518],
         [0.8893, 0.2962, 0.7912, 0.0276, 0.5717, 0.0549],
         [0.1553, 0.7973, 0.4178, 0.7338, 0.2590, 0.7351],
         [0.1428, 0.2820, 0.6108, 0.1845, 0.2958, 0.7913],
         [0.9513, 0.9172, 0.5822, 0.2644, 0.4903, 0.7624]],

        [[0.6758, 0.1829, 0.7414, 0.5801, 0.2566, 0.4346],
         [0.6567, 0.0586, 0.5090, 0.3874, 0.8362, 0.0810],
         [0.0024, 0.3389, 0.7194, 0.6146, 0.2903, 0.8506],
         [0.8053, 0.4206, 0.5574, 0.6105, 0.5836, 0.5493],
         [0.6051, 0.9803, 0.4818, 0.5266, 0.9943, 0.9524]],

        [[0.3257, 0.7237, 0.7401, 0.7127, 0.3186, 0.7822],
         [0.7256, 0.2928, 0.9040, 0.2676, 0.7782, 

In [61]:
t1 = torch.cat([tensor1,tensor1],dim =1)

In [62]:
t1

tensor([[[0.5046, 0.6684, 0.0238, 0.0734, 0.4376],
         [0.3345, 0.2217, 0.1588, 0.4637, 0.8703],
         [0.8007, 0.6400, 0.2294, 0.1902, 0.2603],
         [0.0829, 0.1971, 0.3112, 0.8721, 0.3244],
         [0.6329, 0.2105, 0.7397, 0.7108, 0.9076],
         [0.2056, 0.8665, 0.4776, 0.5808, 0.6268],
         [0.5046, 0.6684, 0.0238, 0.0734, 0.4376],
         [0.3345, 0.2217, 0.1588, 0.4637, 0.8703],
         [0.8007, 0.6400, 0.2294, 0.1902, 0.2603],
         [0.0829, 0.1971, 0.3112, 0.8721, 0.3244],
         [0.6329, 0.2105, 0.7397, 0.7108, 0.9076],
         [0.2056, 0.8665, 0.4776, 0.5808, 0.6268]],

        [[0.7440, 0.1100, 0.5665, 0.2272, 0.3090],
         [0.1998, 0.5057, 0.7349, 0.3224, 0.3077],
         [0.0484, 0.2798, 0.8076, 0.8538, 0.5174],
         [0.4101, 0.4949, 0.8750, 0.0775, 0.0864],
         [0.8816, 0.5973, 0.3059, 0.3990, 0.0769],
         [0.0047, 0.1007, 0.6146, 0.5630, 0.5695],
         [0.7440, 0.1100, 0.5665, 0.2272, 0.3090],
         [0.1998, 0.5057, 0.7

In [63]:
t1 = torch.cat([tensor1,tensor1],dim =0)

In [64]:
t1

tensor([[[0.5046, 0.6684, 0.0238, 0.0734, 0.4376],
         [0.3345, 0.2217, 0.1588, 0.4637, 0.8703],
         [0.8007, 0.6400, 0.2294, 0.1902, 0.2603],
         [0.0829, 0.1971, 0.3112, 0.8721, 0.3244],
         [0.6329, 0.2105, 0.7397, 0.7108, 0.9076],
         [0.2056, 0.8665, 0.4776, 0.5808, 0.6268]],

        [[0.7440, 0.1100, 0.5665, 0.2272, 0.3090],
         [0.1998, 0.5057, 0.7349, 0.3224, 0.3077],
         [0.0484, 0.2798, 0.8076, 0.8538, 0.5174],
         [0.4101, 0.4949, 0.8750, 0.0775, 0.0864],
         [0.8816, 0.5973, 0.3059, 0.3990, 0.0769],
         [0.0047, 0.1007, 0.6146, 0.5630, 0.5695]],

        [[0.3703, 0.8050, 0.5403, 0.1085, 0.6040],
         [0.8221, 0.0058, 0.5775, 0.1665, 0.2900],
         [0.5516, 0.9394, 0.5325, 0.4447, 0.0666],
         [0.1007, 0.9527, 0.0646, 0.2111, 0.8109],
         [0.8386, 0.3704, 0.8307, 0.2947, 0.3106],
         [0.2516, 0.9790, 0.0042, 0.1317, 0.6959]],

        [[0.6884, 0.4396, 0.4156, 0.4487, 0.2442],
         [0.0051, 0.7431,

In [65]:
t1 = torch.stack([tensor1,tensor1])

In [66]:
t1

tensor([[[[0.5046, 0.6684, 0.0238, 0.0734, 0.4376],
          [0.3345, 0.2217, 0.1588, 0.4637, 0.8703],
          [0.8007, 0.6400, 0.2294, 0.1902, 0.2603],
          [0.0829, 0.1971, 0.3112, 0.8721, 0.3244],
          [0.6329, 0.2105, 0.7397, 0.7108, 0.9076],
          [0.2056, 0.8665, 0.4776, 0.5808, 0.6268]],

         [[0.7440, 0.1100, 0.5665, 0.2272, 0.3090],
          [0.1998, 0.5057, 0.7349, 0.3224, 0.3077],
          [0.0484, 0.2798, 0.8076, 0.8538, 0.5174],
          [0.4101, 0.4949, 0.8750, 0.0775, 0.0864],
          [0.8816, 0.5973, 0.3059, 0.3990, 0.0769],
          [0.0047, 0.1007, 0.6146, 0.5630, 0.5695]],

         [[0.3703, 0.8050, 0.5403, 0.1085, 0.6040],
          [0.8221, 0.0058, 0.5775, 0.1665, 0.2900],
          [0.5516, 0.9394, 0.5325, 0.4447, 0.0666],
          [0.1007, 0.9527, 0.0646, 0.2111, 0.8109],
          [0.8386, 0.3704, 0.8307, 0.2947, 0.3106],
          [0.2516, 0.9790, 0.0042, 0.1317, 0.6959]],

         [[0.6884, 0.4396, 0.4156, 0.4487, 0.2442],
      

In [68]:
tensor1 @ tensor2

tensor([[[0.7220, 0.9148, 1.1859, 1.0061, 1.0251, 1.0118],
         [1.2522, 0.8090, 0.9929, 1.2580, 1.2494, 1.3677],
         [0.8014, 1.3386, 1.3859, 1.1883, 1.0969, 1.3414],
         [1.2102, 0.8316, 0.6031, 0.8149, 1.0242, 1.4280],
         [1.6659, 1.5474, 1.5049, 1.8808, 1.6226, 2.3000],
         [1.3977, 1.2939, 1.4846, 1.4433, 1.5707, 1.9752]],

        [[0.8596, 0.9912, 1.3462, 1.0970, 0.6663, 1.3228],
         [0.9959, 1.1517, 1.2723, 0.8430, 0.7896, 1.1879],
         [1.0109, 1.4524, 1.4273, 0.9307, 0.8908, 1.7106],
         [0.8608, 1.0332, 1.2428, 0.9986, 0.7060, 1.0649],
         [1.1205, 0.7928, 1.7227, 0.9920, 0.8583, 1.2066],
         [0.8095, 1.2020, 1.0164, 0.7117, 0.6641, 1.3401]],

        [[1.2330, 0.9358, 1.4244, 1.2430, 1.5889, 1.3206],
         [0.8703, 0.7008, 1.2604, 1.0884, 0.7690, 1.2167],
         [1.3894, 0.5887, 1.5501, 1.3177, 1.4074, 1.0765],
         [1.3544, 0.9799, 1.1144, 1.0230, 1.7706, 1.0642],
         [1.2373, 0.8851, 1.7219, 1.4841, 1.2470, 1.

In [69]:
tensor1.T

tensor([[[0.5046, 0.7440, 0.3703, 0.6884],
         [0.3345, 0.1998, 0.8221, 0.0051],
         [0.8007, 0.0484, 0.5516, 0.9040],
         [0.0829, 0.4101, 0.1007, 0.8927],
         [0.6329, 0.8816, 0.8386, 0.7579],
         [0.2056, 0.0047, 0.2516, 0.3917]],

        [[0.6684, 0.1100, 0.8050, 0.4396],
         [0.2217, 0.5057, 0.0058, 0.7431],
         [0.6400, 0.2798, 0.9394, 0.7521],
         [0.1971, 0.4949, 0.9527, 0.9327],
         [0.2105, 0.5973, 0.3704, 0.1929],
         [0.8665, 0.1007, 0.9790, 0.4875]],

        [[0.0238, 0.5665, 0.5403, 0.4156],
         [0.1588, 0.7349, 0.5775, 0.2676],
         [0.2294, 0.8076, 0.5325, 0.0280],
         [0.3112, 0.8750, 0.0646, 0.6897],
         [0.7397, 0.3059, 0.8307, 0.9895],
         [0.4776, 0.6146, 0.0042, 0.0222]],

        [[0.0734, 0.2272, 0.1085, 0.4487],
         [0.4637, 0.3224, 0.1665, 0.8125],
         [0.1902, 0.8538, 0.4447, 0.0412],
         [0.8721, 0.0775, 0.2111, 0.2973],
         [0.7108, 0.3990, 0.2947, 0.9178],
     

In [70]:
tensor2 * tensor2

tensor([[[6.4127e-02, 8.2343e-01, 5.2192e-01, 4.3265e-01, 1.5997e-01,
          2.5567e-01],
         [9.4413e-02, 3.2309e-01, 7.4380e-01, 1.6462e-01, 4.5518e-01,
          3.9617e-01],
         [1.5268e-02, 3.5717e-01, 2.1566e-01, 3.3303e-01, 1.3914e-02,
          8.7766e-01],
         [9.6713e-01, 2.5372e-01, 4.5764e-03, 6.7405e-02, 4.4828e-01,
          8.1462e-01],
         [5.1368e-01, 3.4434e-03, 2.7335e-01, 7.1538e-01, 5.3558e-01,
          3.1932e-01]],

        [[2.1807e-01, 4.5934e-02, 8.9466e-01, 5.5562e-01, 1.0229e-01,
          4.2480e-01],
         [7.9083e-01, 8.7710e-02, 6.2607e-01, 7.6116e-04, 3.2681e-01,
          3.0154e-03],
         [2.4112e-02, 6.3567e-01, 1.7457e-01, 5.3845e-01, 6.7074e-02,
          5.4036e-01],
         [2.0405e-02, 7.9520e-02, 3.7306e-01, 3.4040e-02, 8.7470e-02,
          6.2618e-01],
         [9.0493e-01, 8.4124e-01, 3.3892e-01, 6.9884e-02, 2.4044e-01,
          5.8124e-01]],

        [[4.5675e-01, 3.3468e-02, 5.4972e-01, 3.3648e-01, 6.5868e-